"""
Project Euler Problem 29: Distinct Powers

How many distinct terms are in the sequence generated by a^b
for 2 <= a <= 100 and 2 <= b <= 100?
"""

RANGE = 100


# THIS DOESNT WORK BECAUSE I THINK THERE MIGHT BE MULTIPLE
# COMPOSITIONS OF A SINGLE NUMBER! (maybe? or am i wrong)
# this only works if the base are prime?
def solve():
    """Solve Project Euler Problem 29."""
    table = set()
    result = 0
    for a in range(2, RANGE + 1):
        for b in range(2, RANGE + 1):
            if a**b in table:
                continue
            table.add(a**b)
            result += 1

    return result
